apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: ctse-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ctse-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5     
  template:
    metadata:
      labels:
        app: ctse-app
    spec:
      containers:
      - name: product-management-ms
        image: adi752698/product_management_ms:v5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000